

install: ../include/amjImaging.H ../include/amjPImaging.H
	mkdir -p /opt/amj/include
	cp ../include/amjImaging.H /opt/amj/include
	cp ../include/amjPImaging.H /opt/amj/include

uninstall:
	- rm /opt/amj/include/amjImaging.H
	- rm /opt/amj/include/amjPImaging.H
	- rmdir /opt/amj/include
	- rmdir /opt/amj

